on:
  push:
    # Sequence of patterns matched against refs/tags
  pull_request:
  workflow_dispatch:

name: Build, Release and Upload Release Asset

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repo
        uses: actions/checkout@v2

      - name: Latex
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            cd compline
            latexmk --shell-escape --pdflatex=lualatex --pdf
            cd ../
            
      # - name: Github Action for LaTeX
      #   uses: xu-cheng/latex-action@v2
      #   with:
      #     working_directory: compline
      #     root_file: compline.tex
      #     latexmk_use_lualatex: true
      #     latexmk_shell_escape: true

      - uses: actions/upload-artifact@v2
        with:
          name: compline/compline.pdf
          path: compline/compline.pdf
